### ISSUE TITLE
keychecker.py crashes with ValueError in bitcoin.bin_to_b58check

### ISSUE THREAD

**Issue by fredcy** [tezos/fundraiser-tools#2]
When I run keychecker.py it crashes immediately like this:
```
$ python keychecker.py a b c d e f g h i j k l m n o user@example.com testing
public key hash:
Traceback (most recent call last):
  File "keychecker.py", line 47, in <module>
    print "public key hash: ", tezos_pkh(pkh)
  File "keychecker.py", line 24, in tezos_pkh
    return bitcoin.bin_to_b58check(pkh.digest(), magicbyte=434591)
  File "/Users/fcy/Documents/Projects/tezos/fundraiser-tools/pykeychecker/ve/lib/python2.7/site-packages/bitcoin/py2specials.py", line 43, in bin_to_b58check
    inp_fmtd = chr(int(magicbyte)) + inp
ValueError: chr() arg not in range(256)
```

I'm using Python 2.7.10 on macOS 10.12.5.

**Comment by fredcy** [comment]
If I replace the `bin_to_b58check` code with the code found here, https://github.com/vbuterin/pybitcointools/blob/master/bitcoin/py2specials.py#L42-L50, the program runs and does validate my tezos key hash.

It seems that version 1.1.42 of the python bitcoin library cannot handle `magicbyte` values greater than 255 in that function. I don't see any more recent published version of that library. But the latest code in github (as above) does handle such values.

**Comment by tzlibre** [comment]
@fredcy currently the requirements file points at the wrong commit. We fixed it pointing to the correct commit of Vitalik's pybitcointools. This also fixes your `magicbyte` issue.

**Comment by skaht** [comment]
The valid values for magicbyte are only between 0 - 255 inclusive.  The  ```magicbyte``` is the called the ```version``` number by libbitcoin,  see https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-base58check-encode. The version agrees with https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch04.asciidoc#base58-and-base58check-encoding.

Many will be interested in reading https://www.reddit.com/r/tezos/comments/8n58a6/nutz_and_boltz_for_computing_tezos_ico_private/. It provides a test vector that drive bx command lines to compute Tezos ICO private keys.
